version: '3'
services:
  wol-server:
    image: python:3.8-alpine
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: always
    command: sh -c "pip install -r requirements.txt && python app.py"